# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-21 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='balance',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='paid',
            field=models.PositiveIntegerField(db_column='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quanitity',
            field=models.PositiveIntegerField(db_column='Quantity'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.PositiveIntegerField(db_column='Amount'),
        ),
    ]
