# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-21 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180421_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='item',
        ),
    ]
