# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-21 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_purchase_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='item',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
