# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-21 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_purchase_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='quanitity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Purchase'),
        ),
        migrations.AddField(
            model_name='fan',
            name='item',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.Item'),
            preserve_default=False,
        ),
    ]
