# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-21 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20180421_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fan',
            name='item',
        ),
        migrations.AddField(
            model_name='fan',
            name='purchase',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.Purchase'),
            preserve_default=False,
        ),
    ]
