# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-21 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20180421_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='balance',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
