# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-21 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20180421_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='seller',
            field=models.CharField(db_column='Seller', max_length=150),
        ),
    ]
